### ISSUE TITLE
тестирование работоспособности конкретного ключа 

### ISSUE THREAD

**Issue by sgrinko** [postgrespro/mamonsu#19]
в идеале нужно иметь возможность проверки работы конкретного item по его ключу, как с пассивным агентом:
zabbix_get -k ключ -s хост
используя утилиту zabbix_get

**Comment by vadv** [comment]
чтобы мониторить состояние самого агента, прикручу статус в json.

**Comment by dan-aksenov** [comment]
Не хватает дебаг-диагностики по конкретным плагинам. Например: 
[ERROR] 2016-07-13 14:12:26,843 - BGWRITER      -       Plugin exception [ProgrammingError]: (u'ERROR', u'57014', u'canceling statement due to statement timeout', u'postgres.c', u'2967', u'ProcessInterrupts', u'', u'')
что за таймаут, если большинство тестов работает?

**Comment by DantePinky** [comment]
или с самого хоста:
zabbix_agentd -t <key>

**Comment by vadv** [comment]
в версии 1.6.0 появилось:
* `mamonsu agent version` выводит запущеную, как сервис, версию mamonsu
* `mamonsu agent metric-list` выводит список метрик, их значений и unixts когда они были получены
* `mamonsu agent metric-get <key>` выводит метрику, значение и unixts когда она была получена

Если на машине запушено несколько mamonsu, или вы изменили что-то в секции api конфиг-файла (скрыто из документации), то необходимо указывать путь до конфига
