### ISSUE TITLE
Ошибки в журналах

### ISSUE THREAD

**Issue by lsconst** [postgrespro/mamonsu#82]
Добрый день!
PostgresPro 9.5.5
1. agent.log - [INFO] 2016-12-18 00:01:57,559 - PGSTATSTATEMENT	-	Extension 'pg_stat_statements' is not installed   -  но расширение установлено и вроде как почти все работает (см. п .2)  
2. agent.log - INFO] 2016-12-18 00:01:57,561 - PGWAITSAMPLING	-	disable plugin: Disable plugin and exit, because 'pg_wait_sampling' extension is not installed. Enable it in PostgreSQL instance: 'host=127.0.0.1 
db=mamonsu user=mamonsu port=5432', if needed and restart..
[INFO] 2016-12-18 00:01:57,565 - CFS	-	disable plugin: Disable plugin and exit, because **PostgresPro Enterprise Edition is not detected** [instance: 'host=127.0.0.1 db=mamonsu user=mamonsu port=54
32']   - соответственно часть соответствующих items пустые в zabbix.  Нужен именно Enterprise  или достаточно postgrespro 9.6.x?

3. postgresql.log - 2016-12-18 00:01:57.565 YEKT >ОШИБКА:  функция pgpro_version() не существует (символ 8)
< 2016-12-18 00:01:57.565 YEKT >ПОДСКАЗКА:  Функция с данными именем и типами аргументов не найдена. Возможно, вам следует добавить явные приведения типов.
< 2016-12-18 00:01:57.565 YEKT >ОПЕРАТОР:  select pgpro_version()

**Comment by tarabanton** [comment]
Могу сказать только насчёт первой ошибки. Расширение можеть быть установлено но не подключено к БД.
Попробуйте выполнить в БД mamonsu `CREATE EXTENSION pg_stat_statements;'

**Comment by vadv** [comment]
привет!
1. `agent.log - [INFO] 2016-12-18 00:01:57,559 - PGSTATSTATEMENT	-	Extension 'pg_stat_statements' is not installed` не установлено в той db, к которой подключен mamonsu по умолчанию (секция [postgres] в agent.conf), выполните `create extension pg_stat_statements` и пропишите его в секцию libraries в postgres.conf. альтернативный способ - выполнить mamonsu tune (будьте осторожны, настроит as is и ответственности не несу).

2. `[INFO] 2016-12-18 00:01:57,565 - CFS	-	disable plugin: Disable plugin and exit, because PostgresPro Enterprise Edition is not detected` - это не ошибка, *INFO* сообщает о том, почему данный плагин не запущен

3. `2016-12-18 00:01:57.565 YEKT >ОПЕРАТОР: select pgpro_version()` - а это последствия пункта 2 (проверяется один раз после старта)

**Comment by lsconst** [comment]
Спасибо...    create extensions в mamonsu привело к появлению сообщения о том, что pg_stat_statements необходимо включить в shared_preload_libraries .. после корректировки postgresql.conf все стало нормально...
